openapi: 3.0.1
info:
  version: 1.0.0
  title: Hacker News
  description: "This is the Open API documentation for the REST API of our beloved application **Hacker News** deployed at <https://hacker-news-fib.herokuapp.com/>. <br>All operations are executable. Only one operation requires authentication: `deleteTweet`. In this case, you must **Authorize** your request by providing the api_key vaule you got when you created the tweet."
servers:
  - url: 'https://hacker-news-fib.herokuapp.com/'
paths:
    /posts/date:
    get:
      tags:
      - posts
      summary: Get all posts ordered by date
      description: Return all posts ordered by date of creation
      operationId: getPostsByDate
      responses:
        200:
          description: successful operation
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Post'
      security:
      - ApiKeyAuth: []



  /posts/points:
    get:
      tags:
      - posts
      summary: Get all posts ordered by points
      description: Return all posts ordered by points
      operationId: getPostsByPoints
      responses:
        200:
          description: successful operation
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Post'
      security:
      - ApiKeyAuth: []